export const ADD_SESSION = 'ADD_SESSION'
export const SELECT_SESSION = 'SELECT_SESSION'
export const CREATE_NEW_SESSION = 'CREATE_NEW_SESSION'

export const ADD_CONTACT = 'ADD_CONTACT'
export const REMOVE_CONTACT = 'REMOVE_CONTACT'

export const ADD_EXERCISE = 'ADD_EXERCISE'
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE'

export const SELECT_DATE = 'SELECT_DATE'
